swagger: "2.0"
info:
  description: |
    Backend API to support HotelHopper.cf \
    To see the standardized api responses see the models at the bottom\: 
    SuccessfulResponse for 200, BadRequestResponse for 400, and UnauthorizedResponse for 401 \
    More HTTP Status Codes may be added in the future and similar models will be made avialable.
  version: "1.0.0"
  title: "Hotel Hopper"
host: "staging-api.hotelhopper.cf"
tags:
- name: "auth"
  description: "Authentication methods"
- name: "popular destinations"
- name: "hotels"
  description: "Hotel search, details and more"
- name: "reservations"
  description: "Create, retreive, delete reservations"
- name: "payment methods"
  description: "Create, retreive, delete payment methods"
schemes:
- "https"

paths:
  /auth/login:
    post:
      tags:
      - "auth"
      summary: "Returns auth token and user details"
      description: "Returns a new JWT token with a 24 hour expiry time. Use this token with all authentication requests using the Header('Authorization, 'bearer \\<JWT>')."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - in: body
        name: body
        schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
              password: 
                type: string
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              data:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoYXJsZXNAc2hlYXJzaGFyZS5jb20iLCJpYXQiOjE1NTQ3OTAwNDd9.uLS_-XvoKyAkKHLxlWOA4WkVWf_j3oe_Ss_X2c_H6s4"
                user:
                  firstName: John
                  lastName: Doe
                  email: john.doe@email.com
                  isAdmin: false
        400:
          description: "Bad request"
          schema:
            $ref: '#/definitions/BadRequestResponse'

  /auth/register:
    post:
      tags:
      - "auth"
      summary: "Returns an auth token for further authentication"
      description: "Creates a new user and returns a JWT token with a 24 hour expiry time. Use this token with all authentication requests using the Header('Authorization, 'bearer \\<JWT>')."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - in: body
        name: body
        schema:
            type: object
            required:
              - firstName
              - lastName
              - email
              - password
            properties:
              firstName:
                type: string
              lastName:
                type: string
              email:
                type: string
              password: 
                type: string
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              data:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoYXJsZXNAc2hlYXJzaGFyZS5jb20iLCJpYXQiOjE1NTQ3OTAwNDd9.uLS_-XvoKyAkKHLxlWOA4WkVWf_j3oe_Ss_X2c_H6s4"
        400:
          description: "Bad request"
          schema:
            $ref: '#/definitions/BadRequestResponse'

  /auth/userDetails:
    get:
      tags:
      - "auth"
      summary: "Returns user details based on JWT token"
      description: "Returns user details based on JWT token. The JWT token must not be expired."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - name: Authorization
        in: header
        description: JWT bearer token given on login or signup. Should be in the format 'bearer \<JWT>'.
        required: true
        type: string
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              data:
                user:
                  userId: 1
                  firstName: John
                  lastName: Doe
                  email: John.Doe@email.com
                  isAdmin: false
                  rewardPoints: 580
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/UnauthorizedResponse'

  /auth/forgotPassword:
    post:
      tags:
      - "auth"
      summary: "Sends a reset password link to the provided email."
      description: "Sends a reset password link to the provided email."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - in: body
        name: body
        schema:
            type: object
            required:
              - email
            properties:
              email:
                type: string
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              message: "We've sent a link to your email to reset your password. It expires in 24 hours."
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'

  /auth/resetPassword/<token>:
    get:
      tags:
      - "auth"
      summary: "Verifies the password reset token is still valid"
      description: "Verifies the password reset token is still valid"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              data:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoYXJsZXNAc2hlYXJzaGFyZS5jb20iLCJpYXQiOjE1NTQ3OTAwNDd9.uLS_-XvoKyAkKHLxlWOA4WkVWf_j3oe_Ss_X2c_H6s4"
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'

  /auth/resetPassword:
    patch:
      tags:
      - "auth"
      summary: "Resets the users password given a valid reset token"
      description: "Resets the users password given a valid reset token."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - in: body
        name: body
        schema:
            type: object
            required:
              - password
              - confirmPassword
              - token
            properties:
              password:
                type: string
              confirmPassword:
                type: string
              token:
                type: string
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              message: "Your password has been succesfully updated. Please log in to get a new token."
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'

  /popularDestinations:
    get:
      tags:
      - "popular destinations"
      summary: "Returns popularly searched cities "
      description: "Returns the city name and image url for our 4 most popular destinations."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: '#/definitions/PopularCitiesResponse'

  #Hotels
  /hotels:
    get:
      tags:
      - "hotels"
      summary: "Returns an array of hotels"
      description: "Returns an array of hotels based on the given searh parameters. Pagination can be acheived using the `page` and `perPage` parameters. By default `page` is **1** and `perPage` is **15**. Only hotels which have enough rooms to acommodate the number of `persons` will be returned. Hotels will also be restricted a 5 mile radius from the given coordinates."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - name: latitude
        in: query
        type: number
        required: true
        description: 'Provide a float value for the latitude of the city center being searched. Ex: 37.3440232'
      - name: longitude
        in: query
        type: number
        required: true
        description: 'Provide a float value for the longitude of the city center being searched. Ex: -121.8738311'
      - name: startDate
        in: query
        type: string
        required: true
        description: 'Must be a date in the format YYYY-MM-DD'
      - name: endDate
        in: query
        type: string
        required: true
        description: 'Must be a date in the format YYYY-MM-DD'
      - name: persons
        in: query
        type: integer
        required: true
        description: 'The amount of people traveling'
      - name: page
        in: query
        type: integer
        description: 'Skips (page * perPage) number of hotels'
        default: 1
      - name: perPage
        in: query
        type: integer
        description: 'The number of hotels to be returned'
        default: 15
      responses:
        200:
          description: "OK"
          schema:
            $ref: '#/definitions/HotelSearchResponse'
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'

  /hotels/:id:
    get:
      tags:
      - "hotels"
      summary: "Returns a hotels details, available rooms, and amenities"
      description: "Returns the full details of the hotel and the available rooms given the `startDate` and `endDate` of the trip."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - name: startDate
        in: query
        type: string
        required: true
        description: 'Must be a date in the format YYYY-MM-DD'
      - name: endDate
        in: query
        type: string
        required: true
        description: 'Must be a date in the format YYYY-MM-DD'
      responses:
        200:
          description: "OK"
          schema:
            $ref: '#/definitions/HotelInfoResponse'
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/UnauthorizedResponse'

  # Reservations
  /reservations/:
    post:
      tags:
      - "reservations"
      summary: "Create a new reservation"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - name: body
        in: body
        schema:
          $ref: '#/definitions/CreateReservationRequest'
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              message: "Your reservation has been successfully created!"
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
    get:
      tags:
      - "reservations"
      summary: "Get all your reservations"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: '#/definitions/ReservationListResponse'
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
# Payment Methods
  /users/paymentMethods:
    post:
      tags:
      - "payment methods"
      summary: "Add a new payment method using a token retrieved form stripe.js. 
                Make sure to use the stripe publishable key pk_test_jb9MEwI7swz2HaPrZXzMQSSL00stxhlhgd"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            token:
              type: string
          example:
            token: "tok_1EUlWOJJU2YEsvxm15TqaGzd"
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              message: "Card added successfully"
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
    delete:
      tags:
      - "payment methods"
      summary: "Deletes a payment method from the user given its id."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
      - name: body
        in: body
        schema:
          type: object
          properties:
            paymentMethodId:
              type: string
          example:
            paymentMethodId: "card_1EPjc0JJU2YEsvxmCaZn280J"
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              message: "Card removed successfully"
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/UnauthorizedResponse'
    get:
      tags:
      - "payment methods"
      summary: "Retrieves all of the saved payment methods"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            type: object
            example:
              error: false
              data: "Array of stripe card objects. See https://stripe.com/docs/api/cards/object"
        400:
          description: "Bad Request"
          schema:
            $ref: '#/definitions/BadRequestResponse'
        401:
          description: "Unauthorized"
          schema:
            $ref: '#/definitions/UnauthorizedResponse'      


securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  SuccessfulResponse:
    type: object
    properties:
      error:
        type: boolean
      message:
        type: string
      data:
        type: object
        description: "Contains various data depending on the api"
    required:
    - error
  BadRequestResponse:
    type: object
    properties:
      error:
        type: boolean
      message:
        type: string
        description: "The first found validation error"
      validationErrors:
        type: object
        properties:
          <name of parameter>:
            type: array
            description: "Array of the problems with the parameter value"
            items:
              type: string
    required:
    - error
    - message
  UnauthorizedResponse:
    type: object
    properties:
      error:
        type: boolean
      message:
        type: string
        enum:
          - "No user found with JWT"
          - "Invalid JWT format"
          - "Expired JWT"
    required:
    - error
    - message
  HotelSearchResponse:
    type: object
    properties:
      error:
        type: boolean
      data:
        type: array
        items:
          $ref: '#/definitions/Hotel'
  HotelInfoResponse:
    type: object
    properties:
      error:
        type: boolean
      data:
        $ref: '#/definitions/FullHotel'
  PopularCitiesResponse:
    type: object
    properties:
      error:
        type: boolean
    example:
      error: false
      data:
        destinations:
          - city: "Chicago"
            url: "https://s3.amazonaws.com/hotel-hopper-bucket1/chicago.png"
          - city: "Los Angeles"
            url: "https://s3.amazonaws.com/hotel-hopper-bucket1/los-angeles.png"
  Hotel:
    type: object
    properties:
      hotelId:
        type: integer
      title: 
        type: string
      description:
        type: string
      street:
        type: string
      city:
        type: string
      state:
        type: string
      zip:
        type: string
      country:
        type: string
      address:
        type: string
      mapURL:
        type: string
      imageURL:
        type: string
      stars:
        type: integer
      rating:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      lowestPrice:
        type: number
  FullHotel:
    type: object
    properties:
      hotelId:
        type: integer
      title: 
        type: string
      description:
        type: string
      street:
        type: string
      city:
        type: string
      state:
        type: string
      zip:
        type: string
      country:
        type: string
      address:
        type: string
      mapURL:
        type: string
      imageURL:
        type: string
      stars:
        type: integer
      rating:
        type: integer
      latitude:
        type: number
      longitude:
        type: number
      rooms:
        type: array
        items:
          type: object
          properties:
            title:
              type: string
            description:
              type: string
            persons:
              type: integer
            beds:
              type: integer
            available:
              type: integer
      hotelAmenities:
        type: array
        items:
          type: object
          properties:
            amenityId:
              type: integer
            amenity:
              type: object
              properties:
                title:
                  type: string
                imageUrl:
                  type: string
  ReservationListResponse:
    type: object
    properties:
      error:
        type: boolean
      data:
        type: array
        items:
          $ref: '#/definitions/ReservationDetail'
  CreateReservationRequest:
    type: object
    properties:
      hotelId:
        type: integer
      startDate:
        type: string
      endDate:
        type: string
      stripeToken:
        type: string
      rooms:
        type: array
        items:
          type: object
          properties:
            roomTypeId:
              type: string
            count:
              type: integer
  ReservationDetail:
    type: object
    properties:
      reservationId:
        type: integer
      hotelId:
        type: integer
      startDate:
        type: string
      endDate:
        type: string
      totalCost:
        type: integer
      status:
        type: string
      reservedRooms:
        type: array
        items:  
          type: object
          properties:
            count:
              type: integer
            roomType:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                persons:
                  type: integer
                beds:
                  type: integer

externalDocs:
  description: "More information can be found on at the github repo"
  url: "https://github.com/CharlesLeonius/HotelHopperServer"
